networks:
  mg_projects:
    driver: bridge
services:
  nginx:
    networks:
      - mg_projects
    ports:
      - 80:80
  molgenis:
    networks:
      - mg_projects
    ports:
      - 8080:8080
  postgresql:
    networks:
      - mg_projects
    ports:
      - 5432:5432
  elasticsearch:
    networks:
      - mg_projects
    ports:
      - 9200:9200
      - 9300:9300
  minio:
    networks:
      - mg_projects
    ports:
      - 9000:9000
  opencpu:
    networks:
      - mg_projects
    ports:
      - 8004:8004
      - 8787:8787
version: "3.8"
